server:
  port: 9090
spring:
  application:
    name: PRODUCT-SERVICE
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:9092}


  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb?createDatabaseIfNotExist=true
    username: root
    password: deependra
    driver-class-name : com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true









